name: Get Package Version
description: Reads version from package.json and exposes it as an output.

inputs:
  path:
    description: Path to package.json file
    required: false
    default: 'package.json'

outputs:
  version:
    description: The version field from the package.json file

runs:
  using: node20
  main: ../dist/get-version.js
