name: Get Package Version
description: Reads version from package.json and exposes it as an output.

inputs:
  path:
    description: Path to package.json file
    required: false
    default: 'package.json'

outputs:
  version:
    description: The version field from the package.json file
  major:
    description: The major version number
  minor:
    description: The minor version number
  patch:
    description: The patch version number
  build:
    description: The build version number, if any
  prerelease:
    description: The prerelease version number

runs:
  using: node20
  main: ../dist/get-version.js
